version: '2'
config: {  }
jobs:
  build_docker:
    steps:
      - build_image
  publish_docker:
    steps:
      - push_image
  deploy_dev:
    steps:
      - deploy_dev:
          cluster: dev
          namespace: marketplace
          workload: tiki-miniapp-docs
          spinnaker_pipeline: generic-v2
          deployment_config: dev
  deploy_prod:
    steps:
      - deploy_production:
          cluster: k8s-marketplace-prod
          namespace: default
          workload: tiki-miniapp-docs
          spinnaker_pipeline: generic-v2
          deployment_config: prod
environment:
  BUILD_IMAGE: 'maven:3.6-jdk-11'
workflows:
  jenkins_pipeline:
    jobs:
      - build_docker:
          filters:
            branches:
              only:
                - develop
                - main
      - publish_docker:
          requires:
            - build_docker
          filters:
            branches:
              only:
                - develop
                - main
      - deploy_dev:
          requires:
            - publish_docker
          filters:
            branches:
              only:
                - develop
      - deploy_prod:
          requires:
            - publish_docker
          filters:
            branches:
              only:
                - main
deployment_config:
  dev:
    ingress:
      hosts:
        - host: tiki-miniapp-docs.dev.tiki.services
          paths:
            - path: /
              port: '80'
    replicaCount: 1
  prod:
    ingress:
      hosts:
        - host: tiki-miniapp-docs.tiki.services
          paths:
            - path: /
              port: '80'
    replicaCount: 1
