version: "2"
config:
  slack_notify: true
  slack_channel: tiki-miniapp-ci
jobs:
  build_docker:
    steps:
      - build_image
  publish_docker:
    steps:
      - push_image
  deploy_dev:
    steps:
      - deploy_dev:
          cluster: dev
          namespace: social-commerce
          workload: tiki-miniapp-docs
          spinnaker_pipeline: generic-v2
          deployment_config: dev
  deploy_prod:
    steps:
      - deploy_production:
          cluster: k8s-social-commerce-prod
          namespace: default
          workload: tiki-miniapp-docs
          spinnaker_pipeline: generic-v2
          deployment_config: prod
workflows:
  jenkins_pipeline:
    jobs:
      - build_docker:
          filters:
            branches:
              only:
                - develop
                - master
      - publish_docker:
          requires:
            - build_docker
          filters:
            branches:
              only:
                - develop
                - master
      - deploy_dev:
          requires:
            - publish_docker
          filters:
            branches:
              only:
                - develop
      - deploy_prod:
          requires:
            - publish_docker
          filters:
            branches:
              only:
                - master
deployment_config:
  dev:
    ingress:
      hosts:
        - host: tiki-miniapp-docs.dev.tiki.services
          paths:
            - path: /
              port: "80"
    readinessProbe:
      httpGet:
        path: "/docs/framework/overview"
        port: 80
      failureThreshold: 3
      initialDelaySeconds: 20
      periodSeconds: 15
      successThreshold: 1
      timeoutSeconds: 3
      livenessProbe:
        httpGet:
          path: "/docs/framework/overview"
          port: 80
        failureThreshold: 3
        initialDelaySeconds: 60
        periodSeconds: 60
        successThreshold: 1
        timeoutSeconds: 3
    replicaCount: 1
  prod:
    resources:
      requests:
        cpu: 15m
        memory: 250Mi
    ingress:
      hosts:
        - host: tiki-miniapp-docs.tiki.services
          paths:
            - path: /
              port: "80"
    readinessProbe:
      httpGet:
        path: "/docs/framework/overview"
        port: 80
      failureThreshold: 3
      initialDelaySeconds: 20
      periodSeconds: 15
      successThreshold: 1
      timeoutSeconds: 3
    livenessProbe:
      httpGet:
        path: "/docs/framework/overview"
        port: 80
      failureThreshold: 3
      initialDelaySeconds: 60
      periodSeconds: 60
      successThreshold: 1
      timeoutSeconds: 3
    replicaCount: 1
    resource:
      requests:
        memory: 512Mi
        cpu: 500m
